DESC EMP; -- emp 테이블 구조보기
SELECT *FROM EMP; -- emp 테이블 내용보기

DESC DEPT; -- dept 테이블 구조보기
SELECT *FROM DEPT; --dept 테이블 내용보기

DESC BONUS; -- bonus 테이블 구조보기
SELECT *FROM BONUS; -- bonus 테이블 구조보기

DESC SALGRADE; -- salgrade 테이블 구조보기
SELECT *FROM SALGRADE; -- salgrade 테이블 구조보기

SELECT EMPNO, ENAME, DEPTNO FROM EMP; -- 셀렉한 열만 조회하기

SELECT DISTINCT DEPTNO FROM EMP; -- 열의 중복 제거하기
SELECT DISTINCT DEPTNO, JOB FROM EMP; -- 여러개 열 중복 제거하기

SELECT ALL JOB,DEPTNO FROM EMP; -- 중복되는 열 제거없이 모든걸 출력

SELECT ENAME, SAL, SAL*12+COMM, COMM FROM EMP; --연산식 사용해서 출력하기
SELECT SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+SAL+COMM FROM EMP; -- 위와 결과 같음
SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL, COMM FROM EMP; -- 별칭 지정해서 사용하기

SELECT * FROM EMP ORDER BY SAL; -- EMP 테이블 모든열을 SAL을 기준으로 오름차순 정렬
SELECT * FROM EMP ORDER BY SAL DESC; --EMP 테이블의 모든열을 SAL 기준으로 내림차순 정렬
SELECT * FROM EMP ORDER BY DEPTNO ASC, SAL DESC; -- DEPTNO 기준 오름차순, SAL기준 내림차순 정렬

SELECT * FROM EMP WHERE DEPTNO = 30; -- DEPTNO가 30인 데이터만 출력

SELECT * FROM EMP WHERE DEPTNO =30 AND JOB = 'SALESMAN'; -- AND 연산자로 조건식 사용
SELECT * FROM EMP WHERE DEPTNO =30 OR JOB = 'CLERK'; -- OR 연산자 조건식 사용

SELECT * FROM EMP WHERE SAL*12 = 36000; -- WHERE절 산술 연산자 사용
SELECT * FROM EMP WHERE SAL >=3000; -- 대소 비교 연산자 사용
SELECT * FROM EMP WHERE ENAME >= 'F'; -- 문자로 대소비교 연산자 사용 (문자가 하나일때)
SELECT * FROM EMP WHERE ENAME <= 'FORZ'; -- 문자열로 대소비교 연산자 사용 (문자가 여러개일때)

-- SAL이 3000인 데이터 조회
SELECT * FROM EMP WHERE SAL = 3000; -- 등가비교 (=) 연산자 사용
-- SAL이 3000이 아닌 데이터를 조회할 때
SELECT * FROM EMP WHERE SAL != 3000; -- 등가비교 (!=) 연산자 사용
SELECT * FROM EMP WHERE SAL <> 3000; -- 등가비교 (<>) 연산자 사용
SELECT * FROM EMP WHERE SAL ^= 3000; -- 등가비교 (^=) 연산자 사용

SELECT * FROM EMP WHERE NOT SAL = 3000; -- 논리부정연산자(NOT)사용

SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB = 'SALESMAN' OR JOB = 'CLERK';
-- OR 연산자를 사용해 여러 개 조건을 만족하는 데이터 출력
SELECT * FROM EMP WHERE JOB IN ('MANAGER','SALESMAN','CLERK');
-- IN 연산자를 사용하여 조건식을 간단하게 출력
SELECT * FROM EMP WHERE JOB != 'MANAGER' AND JOB <> 'SALESMAN' AND JOB ^= 'CLERK';
-- 등가비교 연산자와 AND를 사용해 출력
SELECT * FROM EMP WHERE JOB NOT IN ('MANAGER','SALESMAN','CLERK');
-- IN연산자와 논리 부정 연산자 사용하여 출력

SELECT * FROM EMP WHERE SAL >=2000 AND SAL <=3000; -- 대소비교 연산자와 AND 연산자 사용
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 3000; -- BETWEEN A AND B 연산자 사용
SELECT * FROM EMP WHERE SAL NOT BETWEEN 2000 AND 3000; -- NOT BETWEEN A AND B 논리부정 연산자 사용

-- LIKE 연산자 사용
SELECT * FROM EMP WHERE ENAME LIKE 'S%' ; -- ENAME 첫글자가 S로 시작하는 데이터 찾기
SELECT * FROM EMP WHERE ENAME LIKE '_L%'; -- ENAME 두번째 글자가 L로 시작하는 데이터 찾기
SELECT * FROM EMP WHERE ENAME LIKE '%AM%'; -- ENAME에 AM이라는 글자가 포함된 데이터 찾기
SELECT * FROM EMP WHERE ENAME NOT LIKE '%AM%'; -- NOT LIKE 논리부정 연산자 사용


SELECT ENAME, SAL, SAL+12+COMM AS ANNSAL, COMM FROM EMP; -- 별칭으로 열이름 출력

SELECT *FROM EMP WHERE COMM = NULL; -- 등가 비교 연산자로 NULL 비교 
SELECT * FROM EMP WHERE COMM IS NULL; -- IS NULL 을 사용하여 NULL 데이터 출력
SELECT * FROM EMP WHERE MGR IS NOT NULL; -- MGR이 NULL인 데이터는 출력이 안됨
SELECT * FROM EMP WHERE SAL > NULL AND COMM IS NULL; -- IS NULL과 AND 연산자 사용
SELECT * FROM EMP WHERE SAL > NULL OR COMM IS NULL; -- IS NULL과 OR 연산자 사용


-- 집합 연산자 UNION 사용하기
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO =10 UNION SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO =20;
-- DEPTNO가 10, 20인 EMPNO, ENMAE, SAL,DEPTNO 데이터 모두 출력됨
-- SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10 UNION SELECT EMPNO, ENAME, SAL FROM EMP WHERE DEPTNO = 20;
-- 출력 열의 개수가 달라서 출력이 안됨
-- SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10 UNION SELECT ENAME, EMPNO, DEPTNO, SAL FROM EMP WHERE DEPTNO = 20;
-- 출력 열의 자료 순서가 달라 출력이 안됨
-- SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO =10 UNION SELECT SAL, JOB, DEPTNO, SAL FROM EMP WHERE DEPTNO = 20;
-- 첫번째와 두번째의 열 이름이 다르고 두번째는 같은 열을 중복으로 셀렉해서 출력된 데이터가 이상함
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10 UNION SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;
-- 첫번째와 두번째 조건식이 아예 일치할 때 UNION 출력값 ( 중복을 제거)
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10 UNION ALL SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;
-- ALL UNION 사용하여 출력하기 (출력결과 데이터가 같을 때) ( 중복을 제거하지 않음)


SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP MINUS SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;
-- 집합연산자 MINUS 사용하기 (DEPTNO가 10인 EMPNO, ENAME, SAL 의 데이터를 출력)
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP  INTERSECT SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;
-- 집합 연산자 INTERSECT 사용하기 ( 교집합 )

-- TEST PRACTICE (P.125~126)

SELECT * FROM EMP WHERE ENAME LIKE '%S'; -- ENAME이 S로 끝나는 데이터 출력
SELECT EMPNO, ENAME, JOB,SAL,DEPTNO FROM EMP WHERE JOB = 'SALESMAN';
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO IN (20, 30) AND SAL > 2000; 
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE  DEPTNO IN (20,30) INTERSECT SELECT EMPNO ,ENAME, SAL, DEPTNO FROM EMP WHERE SAL>2000;
SELECT * FROM EMP WHERE SAL<2000 OR SAL>3000;
SELECT ENAME, EMPNO,SAL,DEPTNO FROM EMP WHERE ENAME LIKE '%E%' AND DEPTNO = 30 AND SAL NOT BETWEEN 1000 AND 2000;
SELECT * FROM EMP WHERE JOB IN ('MANAGER', 'CLERK')AND ENAME NOT LIKE '_L%';


-- 문자 함수 사용하기
SELECT ENAME, UPPER (ENAME), LOWER (ENAME), INITCAP(ENAME) FROM EMP; -- UPPER, LOWER,INITCAP 사용

-- UPPER 함수 사용
SELECT * FROM EMP WHERE UPPER (ENAME) = UPPER ('scott'); -- ENAME이 scott인 데이터 출력 (대문자로 변환)
SELECT * FROM EMP WHERE UPPER (ENAME) LIKE UPPER ('%scott%'); -- ENAME 에 scott이 포함된 데이터 출력 (대문자로 변환)

-- LENGTH 함수 사용
SELECT ENAME, LENGTH(ENAME) FROM EMP; -- LENGTH로 문자열 길이가 나오는 데이터 출력
SELECT ENAME, LENGTH(ENAME) FROM EMP WHERE LENGTH(ENAME) >=5; -- ENAME, ENAME 길이, ENAME이 5보다 같거나 작은 데이터 출력
SELECT LENGTH('한글'), LENGTHB('한글') FROM DUAL; -- LENGTH(문자열길이),LENGTHB(바이트수) 출력하기

-- SUBSTR 함수 사용
SELECT JOB, SUBSTR(JOB,1,2), SUBSTR(JOB,3,2), SUBSTR(JOB,5) FROM EMP; -- (1번째 글자부터 2글자),(3번째글자부터 2글자)(5번째글자부터 출력)


SELECT JOB, SUBSTR(JOB, -LENGTH(JOB)),SUBSTR(JOB, -LENGTH(JOB),2), SUBSTR(JOB, -3) FROM EMP; -- LENGTH & SUBSTR 사용

-- INSTR 함수 사용
SELECT INSTR('HELLO, ORACLE!', 'L') AS INSTR_1, INSTR('HELLO, ORACLE!', 'L',5) AS INSTR_2, INSTR ( 'HELLO, ORACLE!','L',2,2) AS INSTR_3 FROM DUAL;
SELECT * FROM EMP WHERE INSTR(ENAME,'S')>0; -- INSTR을 사용해 ENAME에 S가 있는 데이터 출력
SELECT * FROM EMP WHERE ENAME LIKE '%S%' -- LIKE를 사용해 ENAME에 S가있는 데이터 출력

-- REPLACE 함수 사용
SELECT '010-1234-5678' AS REPLACE_BEFORE, REPLACE('010-1234-5678','-','') AS REPLACE_1, REPLACE('010-1234-5678','-') AS REPLACE_2 FROM DUAL;

-- LAPD, RPAD 함수 사용
SELECT 'Oracle', LPAD ('Oracel','10', '#') AS LPAD_1, RPAD('Oracel','10', '*')AS RPAD_1, LPAD('Oracel','10') AS LPAD_2, RPAD('Oracel','10') AS RPAD_2 FROM DUAL;
 SELECT RPAD('971225-',14,'*') AS RPAD_JMNO,RPAD('010-1234-',13,'*') AS RPAD_PHONE FROM DUAL;

-- CONTACT 함수 사용
SELECT CONCAT(EMPNO, ENAME), CONCAT (EMPNO, CONCAT(':',ENAME)) FROM EMP WHERE ENAME = 'SCOTT';
SELECT EMPNO || ENAME, EMPNO || ':' || ENAME FROM EMP WHERE ENAME= 'SCOTT'; -- || 연산자로 출력해보기

-- TRIM , LTRIM, RTRIM 함수 사용 ( 삭제할 문자가 없을 때)
SELECT '[' || TRIM ('__Oracle__')||']' AS TRIM, 
'[' || TRIM(LEADING FROM'__Oracle__')||']'AS TRIM_LEADING,
'['||TRIM(TRAILING FROM'__Oracle__')||']' AS TRIM_TRAILING,
'[' || TRIM(BOTH FROM '__Oracle__')||']' AS TRIM_BOTH FROM DUAL;
-- TRIM , LTRIM, RTRIM 함수 사용 ( 삭제할 문자가 있을 때)
SELECT '['||TRIM('_' FROM '__Oracle__')||']' AS TRIM,'['|| TRIM(LEADING'_' FROM '__Oracle__')||']' AS TRIM_LEADING,'['|| TRIM(TRAILING'_' FROM '__Oracle__')||']' AS TRIM_TRAILING,'['|| TRIM(BOTH'_' FROM '__Oracle__')||']' AS TRIM_BOTH FROM DUAL;


SELECT '[' || TRIM('_Oracle_')|| ']' AS TRIM,'[' || LTRIM(' _Oracle_ ') || ']' AS LTRIM,'[' || LTRIM('<_Oracle_>','_<')|| ']' AS LTRIM_2,'[' || RTRIM(' _Oracle_ ') || ']' AS RTRIM,'[' || RTRIM('<_Oracle_>', '>_')||']' AS RTRIM_2 FROM DUAL;


-- ROUND (숫자, 반올림자리위치) 함수 사용
SELECT ROUND(1234.5678) AS ROUND, ROUND (1234.5678, 0) AS ROUND_0,ROUND (1234.5678, 1) AS ROUND_1,ROUND (1234.5678, 2) AS ROUND_2,ROUND (1234.5678, -1) AS ROUND_MINUS1,ROUND (1234.5678, -2) AS ROUND_MINUS2 FROM DUAL;

-- TRUNC (숫자. 버림위치) 함수 사용
SELECT TRUNC(1234.5678) AS TRUNC, TRUNC (1234.5678, 0) AS ROUND_0,TRUNC (1234.5678, 1) AS TRUNC_1,TRUNC (1234.5678, 2) AS TRUNC_2,TRUNC (1234.5678, -1) AS TRUNC_MINUS1,TRUNC (1234.5678, -2) AS TRUNC_MINUS2 FROM DUAL;

-- CEIL(가장 큰 정수 반환), FLOOR (가장 작은 정수반환) 함수 사용
SELECT CEIL(3.14), FLOOR  (3.14), CEIL (-3.14), FLOOR(-3.14) FROM DUAL;

-- MOD (나머지 숫자 구하기) 함수 사용
SELECT MOD (15,6), MOD(10,2), MOD(11,2) FROM DUAL;



-- 날짜 데이터 사용하기 
--SYSDATE 함수(날짜출력)
SELECT SYSDATE AS NOW, SYSDATE -1 AS YESTERDAY, SYSDATE+1 TOMORROW FROM DUAL; 
-- ADD_MONTHS 함수(몇개월 이후 날짜 출력)
SELECT SYSDATE, ADD_MONTHS (SYSDATE,3) FROM DUAL;

-- 입사 10주년 되는 사원 데이터 출력
SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 120) AS WORK10YEAR FROM EMP;
-- 입사 32년 미만 사원 데이터 출력
SELECT EMPNO, ENAME, HIREDATE,SYSDATE FROM EMP WHERE ADD_MONTHS(HIREDATE,384) > SYSDATE;

-- MONTHS_BETWEEN (날짜 간 개월 수 차이)
SELECT EMPNO, ENAME, HIREDATE, SYSDATE, MONTHS_BETWEEN(HIREDATE,SYSDATE)AS MONTHS1, MONTHS_BETWEEN(SYSDATE, HIREDATE) AS MONTHS2, TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) AS MONTHS3 FROM EMP;

-- NEXT_DAY(돌아오는 요일), LAST_DAY (달의 마지막 날짜) 함수
SELECT SYSDATE, NEXT_DAY(SYSDATE, '월요일'), LAST_DAY(SYSDATE) FROM DUAL;
-- ROUND (날짜 반올림)
SELECT SYSDATE, ROUND (SYSDATE, 'CC') AS FORMAT_CC,ROUND (SYSDATE, 'YYYY') AS FORMAT_YYYY, ROUND(SYSDATE, 'Q')AS FORMAT_Q, ROUND(SYSDATE, 'DDD') AS FORMAT_DDD, ROUND(SYSDATE, 'HH') AS FORMAT_HH FROM DUAL;

--TRUNC (날짜 버림)
SELECT SYSDATE, TRUNC (SYSDATE, 'CC') AS FORMAT_CC,TRUNC (SYSDATE, 'YYYY') AS FORMAT_YYYY, TRUNC(SYSDATE, 'Q')AS FORMAT_Q, TRUNC(SYSDATE, 'DDD') AS FORMAT_DDD, TRUNC(SYSDATE, 'HH') AS FORMAT_HH FROM DUAL;

-- 자료형 변환 함수
-- 숫자를 더해서 출력하기
SELECT EMPNO, ENAME, EMPNO + '500' FROM EMP WHERE ENAME = 'SCOTT'; 
-- 문자와 숫자를 더해서 출력하기
-- SELECT 'ABCD' + EMPNO, EMPNO FROM EMP WHERE ENAME = 'SCOTT';
-- 숫자처럼 보이는 문자는 숫자로 바꿔서 출력이 되지만 그게 아닌건 출력이 안됨

-- TO_CHAR 함수 ( 날짜,숫자 데이터를 문자 데이터로 변환)
SELECT TO_CHAR (SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS 현재날짜시간 FROM DUAL;
-- 월과 요일을 다양한 형식으로 출력(MM,MON,MONTH,DD,DY,DAY)
SELECT SYSDATE, TO_CHAR (SYSDATE, 'MM') AS MM, TO_CHAR (SYSDATE, 'MON') AS MON, TO_CHAR (SYSDATE, 'MONTH') AS MONTH,TO_CHAR (SYSDATE, 'DD') AS DD, TO_CHAR(SYSDATE, 'DY') AS DY,TO_CHAR (SYSDATE, 'DAY') AS DAY FROM DUAL;
-- 여러 언어로 날짜(월)출력
SELECT SYSDATE, TO_CHAR(SYSDATE, 'MM'),  TO_CHAR(SYSDATE,'MON', 'NLS_DATE_LANGUAGE = KOREAN') AS MON_KOR,
TO_CHAR(SYSDATE,'MON', 'NLS_DATE_LANGUAGE = JAPANESE') AS MON_JPN,
TO_CHAR(SYSDATE,'MON', 'NLS_DATE_LANGUAGE = ENGLISH') AS MON_ENG,
TO_CHAR(SYSDATE,'MONTH', 'NLS_DATE_LANGUAGE = KOREAN') AS MONTH_KOR,
TO_CHAR(SYSDATE,'MONTH', 'NLS_DATE_LANGUAGE = JAPANESE') AS MONTH_JPN,
TO_CHAR(SYSDATE,'MONTH', 'NLS_DATE_LANGUAGE = ENGLISH') AS MONTH_ENG FROM DUAL;
-- 여러 언어로 날짜(요일)출력
SELECT SYSDATE, TO_CHAR(SYSDATE, 'MM'),  TO_CHAR (SYSDATE, 'DD') AS DD,
TO_CHAR(SYSDATE,'DY', 'NLS_DATE_LANGUAGE = KOREAN') AS DY_KOR,
TO_CHAR(SYSDATE,'DY', 'NLS_DATE_LANGUAGE = JAPANESE') AS DEY_JPN,
TO_CHAR(SYSDATE,'DY', 'NLS_DATE_LANGUAGE = ENGLISH') AS DY_ENG,
TO_CHAR(SYSDATE,'DAY', 'NLS_DATE_LANGUAGE = KOREAN') AS DAY_KOR,
TO_CHAR(SYSDATE,'DAY', 'NLS_DATE_LANGUAGE = JAPANESE') AS DAY_JPN,
TO_CHAR(SYSDATE,'DAY', 'NLS_DATE_LANGUAGE = ENGLISH') AS DAY_ENG FROM DUAL;
-- SYSDATE 시간 형식 지정 출력
SELECT SYSDATE, TO_CHAR(SYSDATE, 'HH24:MI:SS') AS HH24MISS,
TO_CHAR(SYSDATE, 'HH12:MI:SS AM') AS HHMISS_AM,
TO_CHAR(SYSDATE, 'HH:MI:SS P.M.') AS HHMISS_PM
FROM DUAL;
-- 숫자 데이터 형식 지정 출력
SELECT SAL,TO_CHAR (SAL, '$999,999') AS SAL_$,
TO_CHAR (SAL, 'L999,999') AS SAL_L,
TO_CHAR (SAL, '999,999.00') AS SAL_1,
TO_CHAR (SAL, '000,999,999,00') AS SAL_2,
TO_CHAR (SAL, '000999999.99') AS SAL_3,
TO_CHAR (SAL, '999,999,00') AS SAL_4 FROM EMP;


-- TO_NUMBER ('문자열데이터','인식될숫자형태데이터')(문자 데이터를 숫자 데이터로 변환)
SELECT 1300 - '1500', '1300' + 1500 FROM DUAL;
-- 문자 데이터끼리 연산해서 출력
-- SELECT '1,300' - '1,500' FROM DUAL; --(출력이안됨)
SELECT TO_NUMBER ('1,300', '999,999')- TO_NUMBER('1,500', '999,999') FROM DUAL;

-- TO_DATE ('문자데이터' , '인식될 날짜데이터') (문자 데이터를 날짜 데이터로 변환)
SELECT TO_DATE ('2018-07-14','YYYY-MM-DD')AS TODATE1, TO_DATE('20180714','YYYY-MM-DD') AS TODATE2 FROM DUAL;

-- 1981.06.01 이후에 입사한 사원 정보 출력
SELECT* FROM EMP WHERE HIREDATE>TO_DATE('1981/06/01','YYYY/MM/DD') ;

-- 여러가지 형식으로 날짜 데이터 출력
SELECT TO_DATE ('49/12/10', 'YY/MM/DD') AS YY_YEAR_49, TO_DATE ('49/12/10', 'RR/MM/DD') AS RR_YEAR_49,TO_DATE ('50/12/10', 'YY/MM/DD') AS YY_YEAR_50,TO_DATE ('50/12/10', 'RR/MM/DD') AS RR_YEAR_50,TO_DATE ('51/12/10', 'YY/MM/DD') AS YY_YEAR_51,TO_DATE ('51/12/10', 'RR/MM/DD') AS RR_YEAR_51 FROM DUAL;

-- NULL 처리 함수
-- NVL ([NULL인지 여부검사 데이터] ,[앞의 데이터가 NULL일 경우 반환할 데이터]) 
SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM, NVL (COMM,0), SAL+NVL (COMM,0) FROM EMP;
-- NVL2 ([NULL인지 여부검사 데이터], [앞 데이터가 NULL이 아닐경우 반환할 데이터 또는 계산식],[앞 데이터가 NULL일 경우 반환할 데이터 또는 계산식])(반환할 데이터를 추가로 지정 가능)
SELECT EMPNO, ENAME, COMM, NVL2 (COMM,'0','X') , NVL2(COMM, SAL*12+COMM, SAL*12) AS ANNSAL FROM EMP;


-- 상황에 따라 다른 데이터를 반환
-- DECODE 함수 (기준이 되는 데이터를 지정 후 값에 따라 다른 결과를 출력)
SELECT EMPNO, ENAME, JOB, SAL, DECODE(JOB, 'MANAGER', SAL*1.1, 'SALESMAN', SAL*1.05, 'ANALYST', SAL, SAL*1.03) AS UPSAL FROM EMP;
-- CASE문 (DECODE 함수와 같은 방식으로 사용
SELECT EMPNO, ENAME, JOB, SAL, CASE JOB WHEN 'MANAGER' THEN SAL*1.1 WHEN 'SALESMAN' THEN SAL*1.05 WHEN 'ANALYST'THEN SAL ELSE SAL*1.03 END AS UPSAL FROM EMP;
-- 기준 데이터 없이 CASE문 사용
SELECT EMPNO, ENAME, COMM, CASE WHEN COMM IS NULL THEN '해당사항 없음' WHEN COMM = 0 THEN '수당없음' WHEN COMM >0 THEN '수당 : ' || COMM END AS COMM_TEXT FROM EMP;

-- TEST PRACTICE P174~175


-- 다중행 함수
-- SUM 함수 (합계)
SELECT SUM(SAL) FROM EMP; -- 모두 합쳐져 1개의 행으로 출력됨
SELECT ENAME, SUM(SAL) FROM EMP; -- SUM은 한 행으로 나오고 ENAME은 여러행이라 오류 발생
--추가 수당 합계 구하기
SELECT SUM(COMM) FROM EMP;
-- DISTINCT, ALL 함수 사용해서 합계 구하기
SELECT SUM(DISTINCT SAL), SUM(ALL SAL), SUM(SAL) FROM EMP;


-- COUNT 함수 ( 데이터 개수)
SELECT COUNT(*)FROM EMP;
SELECT COUNT(*)FROM EMP WHERE DEPTNO=30;
-- COUNT, DISTINCT, ALL 함수 사용해 급여 개수 구하기
SELECT COUNT (DISTINCT SAL), COUNT (ALL SAL), COUNT(SAL) FROM EMP;
-- COMM 열 개수 출력
SELECT COUNT(COMM)FROM EMP;
-- COUNT, IS NOT NULL 사용
SELECT COUNT (COMM) FROM EMP WHERE COMM IS NOT NULL; -- NULL 이 데이터로 포함되어 있을 경우 NULL 데이터는 반환 개수에서 제외됨
-- IS NOT NULL 조건을 사용해도 같은 결과 값이 출력

--MAX, MIN 함수
SELECT MAX(SAL) FROM EMP WHERE DEPTNO =10;
SELECT MIN(SAL) FROM EMP WHERE DEPTNO =10;

-- 날짜 데이터에 MAX, MIN 사용
SELECT MAX(HIREDATE) FROM EMP WHERE DEPTNO = 20;
SELECT MIN (HIREDATE) FROM EMP WHERE DEPTNO = 20;

-- 평균 값을 구하는 AVG 함수
SELECT AVG(SAL) FROM EMP WHERE DEPTNO =30;


-- DISTINCT로 중복을 제거한 SAL 열의 평균 SAL 구하기
SELECT AVG(DISTINCT SAL) FROM EMP WHERE DEPTNO = 30;

-- GROUP BY절 (결과값을 원하는 열로 묶어 출력)
SELECT AVG(SAL),'10' AS DEPTNO FROM EMP WHERE DEPTNO = 10 UNION ALL SELECT AVG(SAL), '20' AS DEPTNO FROM EMP WHERE DEPTNO = 20 UNION ALL SELECT AVG(SAL),'30' AS DEPTNO FROM EMP WHERE DEPTNO = 30;
-- GROUP BY 기본사용법
-- DEPTNO 별 평균 SAL 출력
SELECT AVG(SAL), DEPTNO FROM EMP GROUP BY DEPTNO;
-- DEPTNO 및 JOB 별 평균 SAL 로 정렬하기
SELECT DEPTNO, JOB, AVG(SAL) FROM EMP GROUP BY DEPTNO , JOB ORDER BY DEPTNO, JOB;
-- GROUP BY 절에 없는 열을 SELECT 절에 포함하면 오류가 남 
SELECT ENAME, DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO;

-- HAVING 절 (GROUP BY절에 조건 줄 때 사용)
SELECT DEPTNO, JOB , AVG(SAL) FROM EMP GROUP BY DEPTNO, JOB HAVING AVG(SAL)>=2000 ORDER BY DEPTNO, JOB;
-- HAVING 절의 기본 사용법은 ->  HAVING 출력그룹제한조건식 
-- HAVING절 사용 유의점
SELECT DEPTNO,JOB,AVG(SAL) FROM EMP WHERE AVG (SAL)<=2000 GROUP BY DEPTNO, JOB ORDER BY DEPTNO,JOB; -- 그룹일땐 WHERE이 아닌 HAVING을 사용해야해서 오류
-- HAVING과 WHERE의 차이점
SELECT DEPTNO,JOB,AVG(SAL) FROM EMP GROUP BY DEPTNO, JOB HAVING AVG(SAL) >= 2000 ORDER BY DEPTNO,JOB; -- HAVING만 사용 
SELECT DEPTNO,JOB,AVG(SAL) FROM EMP WHERE SAL<=3000 GROUP BY DEPTNO, JOB HAVING AVG(SAL)>=2000 ORDER BY DEPTNO, JOB; -- WHERE과 HAVING 모두 사용

-- 그룹화와 관련된 함수 ( ROLLUP, CUBE, GROUPING SETS)
-- GROUP BY만 사용한 그룹화
SELECT DEPTNO, JOB, COUNT(*),MAX(SAL),SUM(SAL),AVG(SAL) FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO, JOB;
-- ROLLUP 함수를 사용해 그룹화
SELECT DEPTNO, JOB, COUNT(*),MAX(SAL),SUM(SAL),AVG(SAL) FROM EMP GROUP BY ROLLUP (DEPTNO, JOB);
-- CUBE 함수를 사용해 그룹화
SELECT DEPTNO, JOB, COUNT(*),MAX(SAL),SUM(SAL),AVG(SAL) FROM EMP GROUP BY CUBE (DEPTNO, JOB) ORDER BY DEPTNO, JOB;-- ROLLUP 보다 많은 결과가 출력됨 (DEPTNO와 상관없는 결과도 함께 출력됨)
-- DEPTNO를 먼저 그룹화 하고 ROLLUP함수에 JOB 저장
SELECT DEPTNO, JOB, COUNT(*)FROM EMP GROUP BY DEPTNO, ROLLUP(JOB);
-- JOB을 먼저 그룹화하고 ROLLUP함수에 DEPTNO 저장
SELECT DEPTNO, JOB, COUNT(*)FROM EMP GROUP BY JOB, ROLLUP(DEPTNO);
-- GROUPING SETS 함수 ( 같은 수준의 그룹화 열이 여러개일 때 열벌 그룹화)
SELECT DEPTNO, JOB, COUNT(*) FROM EMP GROUP BY GROUPING SETS(DEPTNO,JOB) ORDER BY DEPTNO, JOB;
-- GROUPING함수와 SELECT문 실행
SELECT DEPTNO, JOB, COUNT(*),MAX(SAL),SUM(SAL),AVG(SAL), GROUPING (DEPTNO), GROUPING(JOB) FROM EMP GROUP BY CUBE(DEPTNO, JOB) ORDER BY DEPTNO, JOB;
-- DECODED문으로 GROUPING 함수 적용
SELECT DECODE(GROUPING(DEPTNO),1,'ALL_DEPT', DEPTNO) AS DEPTNO, DECODE (GROUPING(JOB),1,'ALL_JOB',JOB)AS JOB, COUNT(*),MAX(SAL),SUM(SAL),AVG(SAL) FROM EMP GROUP BY CUBE(DEPTNO, JOB) ORDER BY DEPTNO, JOB;
-- GROUPING_ID 함수(한번에 여러열 지정 가능,비트 벡터값으로 출력됨)
SELECT DEPTNO, JOB, COUNT(*), SUM(SAL), GROUPING (DEPTNO), GROUPING (JOB), GROUPING_ID(DEPTNO, JOB) FROM EMP GROUP BY CUBE(DEPTNO, JOB) ORDER BY DEPTNO, JOB;
-- LISTAGG 함수
--1. SELECT로 DEPTNO 10인 데이터 출력
SELECT ENAME FROM EMP WHERE DEPTNO =10;
--2. GROUP BY로 그룹화 하여 DEPTNO, ENAME 출력
SELECT DEPTNO, ENAME FROM EMP GROUP BY DEPTNO, ENAME;
--3. LISTAGG를 사용하여 나란히 나열 출력
SELECT DEPTNO, LISTAGG(ENAME,',') WITHIN GROUP (ORDER BY SAL DESC) AS ENAMES FROM EMP GROUP BY DEPTNO;

-- PIVOT 함수
--1. 기존 출력
SELECT DEPTNO, JOB , MAX(SAL) FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO, JOB;
--2. PIVOT 함수 사용해 행을 열로 바꿔서 출력
SELECT * FROM (SELECT DEPTNO, JOB,SAL FROM EMP) PIVOT(MAX(SAL) FOR DEPTNO IN (10,20,30)) ORDER BY JOB;
--3. PIVOT 함수로 DEPTNO, JOB별 최고 SAL을 출력
SELECT * FROM (SELECT DEPTNO, JOB,SAL FROM EMP) PIVOT(MAX(SAL) FOR JOB IN ('CLERK' AS CLERK, 'SALESMAN' AS PRESIDENT, 'MANAGER' AS MANAGER, 'ANALYST' AS ANALYST)) ORDER BY DEPTNO;
-- DECODE문 활용해 PIVOT 함수와 같은 출력 구현
SELECT DEPTNO, MAX (DECODE(JOB,'CLERK',SAL)) AS "CLERK",
MAX (DECODE(JOB,'SALESMAN',SAL)) AS "SALESMAN",
MAX (DECODE(JOB,'PRESIDENT',SAL)) AS "PRESIDENT",
MAX (DECODE(JOB,'MANAGER',SAL)) AS "MANAGER",
MAX (DECODE(JOB,'ANALYST',SAL)) AS "ANALYST" FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO;

-- UNPIVOT 함수 (열을 행으로 바꿔서 출력)
SELECT * FROM(
SELECT DEPTNO, MAX (DECODE(JOB,'CLERK',SAL)) AS "CLERK",
MAX (DECODE(JOB,'SALESMAN',SAL)) AS "SALESMAN",
MAX (DECODE(JOB,'PRESIDENT',SAL)) AS "PRESIDENT",
MAX (DECODE(JOB,'MANAGER',SAL)) AS "MANAGER",
MAX (DECODE(JOB,'ANALYST',SAL)) AS "ANALYST" FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO)
UNPIVOT( SAL FOR JOB IN(CLERK, SALESMAN,PRESIDENT,MANAGER,ANALYST)) ORDER BY DEPTNO, JOB;


-- !!!!!!!!!!!!!!!조인 (여러 테이블을 하나의 테이블 처럼 사용)

-- FROM절 (여러 테이블 사용)
SELECT * FROM EMP, DEPT ORDER BY EMPNO;
-- 열 이름 비교 조건식 (DEPTNO가 일치하는 두개의 열이 조인돼서 비교)
SELECT * FROM EMP,DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO ORDER BY EMPNO;
-- 테이블의 별칭 설정

-- 조인 종류 ( 등가조인, 비등가조인, 자체조인, 외부조인)
-- 등가조인 (=내부조인, 단순조인)
SELECT EMPNO, ENAME,DEPTNO,DNAME,LOC FROM EMP E, DEPT D WHERE E.DEPTNO =D.DEPTNO; -- 열이름이 같을 때 열 이름을 테이블 구분없이 명시하면 오류발생
SELECT E.EMPNO, E.ENAME,D.DEPTNO,D.DNAME,D.LOC FROM EMP E, DEPT D WHERE E.DEPTNO =D.DEPTNO ORDER BY D.DEPTNO, E.EMPNO; -- 테이블을 구분하여 명시
SELECT E.EMPNO, E.ENAME,E.SAL, D.DEPTNO,D.DNAME,D.LOC FROM EMP E, DEPT D WHERE E.DEPTNO =D.DEPTNO AND SAL >=3000; -- WHERE 절에 조건식을 추가하여 출력
-- 비등가조인 (조인 방식 외의 방식)
SELECT*FROM EMP E, SALGRADE S WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL; -- SAL 범위를 지정하는 조건식으로 조인
-- 자체조인 
-- 같은 테이블을 두번 사용하여 자체 조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR,E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME FROM EMP E1, EMP E2 WHERE E1.MGR =E2.EMPNO;
-- 외부조인 ( 조인 기준 열의 한쪽이 NULL이어도 강제로 출력하는 방식)
SELECT E1.EMPNO, E1.ENAME, E1.MGR,E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME FROM EMP E1, EMP E2 WHERE E1.MGR =E2.EMPNO (+) ORDER BY E1.EMPNO; -- 왼쪽 외부조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR,E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME FROM EMP E1, EMP E2 WHERE E1.MGR(+) = E2.EMPNO  ORDER BY E1.EMPNO -- 오른쪽 외부조인

-- SQL-99 표준문법 조인
-- NATURAL JOIN (등가조인 대신 사용 /자동으로 조인 기준 열을 지정 / 기존 등가 조인과 다르게 조인 기준열을 SELECT 절에 명시할때 테이블 이름을 붙이면 안됨)
SELECT E.EMPNO, E.ENAME, E.JOB,E.MGR, E.HIREDATE, E.SAL,E.COMM, DEPTNO, D.DNAME, D.LOC FROM EMP E NATURAL JOIN DEPT D ORDER BY DEPTNO, E.EMPNO;
-- JOIN ~ USING ( 기존 등가 조인 대신 조인 / USING 키워드에 명시한 열을 조인 기준으로 사용)
SELECT E.EMPNO, E.ENAME, E.JOB,E.MGR, E.HIREDATE, E.SAL,E.COMM, DEPTNO, D.DNAME, D.LOC FROM EMP E JOIN DEPT D USING (DEPTNO) WHERE SAL>= 3000 ORDER BY DEPTNO, E.EMPNO;
-- JOIN ~ ON
SELECT E.EMPNO, E.ENAME, E.JOB,E.MGR, E.HIREDATE, E.SAL,E.COMM, E.DEPTNO, D.DNAME, D.LOC FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO) WHERE SAL>= 3000 ORDER BY DEPTNO, EMPNO; -- ORDER BY 에 있는 EMPNO는 EMP에서 가져오는 EMPNO가 유일하기 때문에 식별이 가능해서 테이블명을 앞에 붙이지 않음
-- OUTER JOIN ( FROM 테이블1 LEFT(OR RIGHT, OR FULL) OUTER JOIN 테이블2 ON (조건식)
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME FROM EMP E1 LEFT OUTER JOIN EMP E2 ON(E1.MGR = E2.EMPNO) ORDER BY E1.EMPNO;-- 왼쪽 외부 조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON(E1.MGR = E2.EMPNO) ORDER BY E1.EMPNO, MGR_EMPNO;-- 오른쪽 외부 조인
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME FROM EMP E1 FULL OUTER JOIN EMP E2 ON(E1.MGR = E2.EMPNO) ORDER BY E1.EMPNO;-- 전체 외부 조인
-- 3개 이상의 테이블을 조인 할 때 (FROM 테이블1 JOIN 테이블2 ON 조건식 JOIN 테이블3 ON 조건식)(FROM 테이블1,테이블2,테이블3 WHERE 테이블1.COL = 테이블2.COL AND 테이블2.COL = 테이블3.COL) 

-- 서브쿼리 ( 괄호로 묶어서 사용, ORDER BY절 사용불가)
-- ENAME이 JONES인 SAL 데이터 출력
SELECT SAL FROM EMP WHERE ENAME = 'JONES';
-- SAL이 2975 보다 높은 ENAME 데이터 출력
SELECT * FROM EMP WHERE SAL >2975;
-- 서브쿼리로 JONES의 SAL보다 높은 SAL을 받는 ENAME 출력
SELECT * FROM EMP WHERE SAL> (SELECT SAL FROM EMP WHERE ENAME ='JONES');

-- 단일행 서브쿼리
-- 1. 날짜형 데이터
SELECT* FROM EMP WHERE HIREDATE<(SELECT HIREDATE FROM EMP WHERE ENAME = 'SCOTT');
-- 2. 단일형 서브쿼리와 함수 (서브쿼리 안에서 함수를 사용)
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL,D.DEPTNO,D.DNAME, D.LOC FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND E.DEPTNO = 20 AND E.SAL> (SELECT AVG(SAL) FROM EMP);

-- 다중행 서브쿼리
-- IN 연산자
SELECT * FROM EMP WHERE DEPTNO IN (20,30); -- DEPTNO 가 20,30인 EMP 데이터 출력
SELECT * FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO); -- MAX SAL과 동일한 SAL인 데이터 출력
SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO; -- DEPTNO별 최대 SAL 출력
-- ANY, SOME 연산자
SELECT*FROM EMP WHERE SAL = ANY (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO); -- ANY
SELECT*FROM EMP WHERE SAL = SOME (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO); -- SOME
-- DEPTNO=30 중 MAX SAL 보다 적은 SAL 받는 데이터 출력
SELECT * FROM EMP WHERE SAL<ANY (SELECT SAL FROM EMP WHERE DEPTNO = 30) ORDER BY SAL,EMPNO; -- 조건이 1개만 맞아도 출력됨
-- DEPTNO=30 중 MIN SAL 보다 많이 SAL 받는 데이터 출력
SELECT * FROM EMP WHERE SAL>ANY (SELECT SAL FROM EMP WHERE DEPTNO = 30);
-- ALL 연산자 (모든 결과가 맞아 떨어져야 조건식이 TRUE)
SELECT * FROM EMP WHERE SAL<ALL (SELECT SAL FROM EMP WHERE DEPTNO = 30);
SELECT * FROM EMP WHERE SAL>ALL (SELECT SAL FROM EMP WHERE DEPTNO = 30); -- > ALL 은 서브쿼리 결과값중 가장 큰값과 비교하여 큰값을 가진 데이터만 출력 됨
-- EXISTS 연산자
-- 1. 서브쿼리 결과값이 존재하는 경우
SELECT* FROM EMP WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO = 10); -- DEPTNO가 10인 결과값이 존재하기 때문에 TRUE가 되어 모두 출력됨
-- 2. 서브쿼리 결과값이 존재하지 않는 경우
SELECT* FROM EMP WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO = 50); -- DEPTNO가 50인 결과값이 존재하지않기 때문에 FALSE 가 되어 모두 출력되지않음

-- 비교열이 여러개인 다중열 서브쿼리
SELECT*FROM EMP WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO); -- DEPTNO를 그룹화하고 SAL이 MAX인 값만 골라 EMP전체를 출력

-- FROM 절에 사용하는 서브쿼리 ( = 인라인뷰) 와 WIHT절
-- 1. 인라인뷰 사용하기 (DEPTNO가 10인 값만 뽑아 E10테이블 생성, DEPT 전체를 D테이블 생성 -> FROM절에 있는 테이블에서 HERE절에 있는 조건식에 해당하는 열만 뽑아 조인)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC FROM (SELECT *FROM EMP WHERE DEPTNO = 10) E10, (SELECT* FROM DEPT) D WHERE E10.DEPTNO = D.DEPTNO; 
-- 2. WITH절 사용 (WITH 테이블1 AS (SELECT 조건식) 테이블2 AS (SELECT 조건식)
WITH E10 AS (SELECT*FROM EMP WHERE DEPTNO = 10), D AS (SELECT*FROM DEPT) SELECT E10.EMPNO, E10.ENAME,E10.DEPTNO, D.DNAME,D.LOC FROM E10, D WHERE E10.DEPTNO = D.DEPTNO;

-- SELECT 절에 사용하는 서브쿼리 ( = 스칼라 서브쿼리)/ 하나의 결과만 반환하도록 작성해 주어야함
SELECT EMPNO, ENAME, JOB,SAL, (SELECT GRADE FROM SALGRADE WHERE E.SAL BETWEEN LOSAL AND HISAL)AS SALGRADE, DEPTNO, (SELECT DNAME FROM DEPT WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME FROM EMP E; -- SALGRADE 열을 생성해 GRADE 데이터를 넣는 조건식을 넣어주고, E테이블과 일치하는 DEPT 테이블 의 부서를 가져와 부서명을 생성함

-- 테이블 데이터 추가하기
CREATE TABLE DEPT_TEMP AS SELECT*FROM DEPT; -- DEPT TEMP 테이블 생성
SELECT * FROM DEPT_TEMP; -- DEPT_TEMP 조회하기

-- INSERT문 (  데이터를 추가하는데 사용 )
INSERT INTO DEPT_TEMP(DEPTNO,DNAME,LOC) VALUES(50, 'DATABASE', 'SEOUL');
SELECT * FROM DEPT_TEMP; -- 위에서 입력한 데이터가 DEPT_TEMP 에 추가되었음
INSERT INTO DEPT_TEMP VALUES (60,'NETWORK','BUSAN');
SELECT*FROM DEPT_TEMP; -- 열지정을 하지않고 값을 입력하면 원래 나열된 순서대로 값이 들어가기 때문에 값을 입력할때 정확히 순서대로 기입해야함

-- NULL 데이터 입력
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC) VALUES (70  ,'WEB',NULL);
SELECT*FROM DEPT_TEMP; -- LOC가 공백으로 출력됨
INSERT INTO DEPT_TEMP (DEPTNO, DNAME,LOC) VALUES (80,'MOBILE','');
SELECT*FROM DEPT_TEMP; -- 공백에 NULL대신 문자열로 입력
INSERT INTO DEPT_TEMP (DEPTNO, LOC) VALUES (90,'INCHEON');
SELECT*FROM DEPT_TEMP; -- NULL의 암시적 입력, NULL이 들어갈 열을 아예 입력하지 않음 , DNAME이 공백으로 출력됨

-- 테이블에 날짜 데이터 입력 (CREATE, INSERT)
CREATE TABLE EMP_TEMP AS SELECT*FROM EMP WHERE 1<>1;
SELECT * FROM EMP_TEMP; -- EMP_TEMP 테이블 생성

INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(9999,'홍길동','PRESIDENT', NULL,'2001/01/01',5000,1000,10);
SELECT*FROM EMP_TEMP; -- 날짜 데이터(/) 입력하기
INSERT INTO EMP_TEMP (EMPNO, ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES (1111,'성춘향','MANAGER',9999,'2001-01-05',4000,NULL,20);
SELECT*FROM EMP_TEMP; -- 날짜 데이터(-) 입력하기
-- INSERT INTO EMP_TEMP (EMPNO, ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES (2111,'이순신','MANAGER',9999,'07/01/2001',4000,NULL,20);
-- SELECT*FROM EMP_TEMP; -- 날짜 데이터 오류 (순서대로 입력하지 않으면 오류가 발생함)
INSERT INTO EMP_TEMP (EMPNO, ENAME,JOB,MGR,HIREDATE, SAL, COMM,DEPTNO) VALUES(2111,'이순신','MANAGER',9999,TO_DATE('07/01/2001','DD/MM/YYYY'),4000,NULL,20);
SELECT*FROM EMP_TEMP; -- TO_DATE를 이용하여 데이터 입력
INSERT INTO EMP_TEMP (EMPNO, ENAME,JOB,MGR,HIREDATE, SAL, COMM,DEPTNO) VALUES(3111,'심청이','MANAGER',9999,SYSDATE,4000,NULL,30);
SELECT*FROM EMP_TEMP; -- SYSDATE 이용하여 데이터 입력

-- 서브쿼리를 사용해 데이터 추가
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM,DEPTNO)
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,E.SAL,E.COMM,E.DEPTNO
FROM EMP E, SALGRADE S 
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE=1;
SELECT * FROM EMP_TEMP; -- EMP에서 SAL이 LOSAL~HISAL 중 1등급인 SAL을 가진 데이터만 출력

-- 테이블에 있는 데이터 수정 (UPDATE, ALTER)
CREATE TABLE DEPT_TEMP2 AS SELECT*FROM DEPT;
SELECT*FROM DEPT_TEMP2; -- DEPT_TEMP2 테이블 생성

-- UPDATE문 기본 사용
UPDATE DEPT_TEMP2 SET LOC ='SEOUL';
SELECT*FROM DEPT_TEMP2; -- DEPT_TEMP2 테이블 업데이트하기
-- 수정한 내용 되돌리기 (커밋 전까지 돌릴 수 있음)
ROLLBACK;
-- 일부분만 수정하기
UPDATE DEPT_TEMP2 SET DNAME='DATABASE', LOC = 'SEOUL' WHERE DEPTNO = 40; 
SELECT * FROM DEPT_TEMP2;

-- 서브쿼리를 사용해 데이터 수정
UPDATE DEPT_TEMP2 SET(DNAME,LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40) WHERE DEPTNO =40;
SELECT* FROM DEPT_TEMP2;
-- 서브쿼리로 일부 데이터 수정
UPDATE DEPT_TEMP2 SET DNAME = (SELECT DNAME FROM DEPT WHERE DEPTNO = 40), LOC = (SELECT LOC FROM DEPT WHERE DEPTNO =40) WHERE DEPTNO =40;
SELECT * FROM DEPT_TEMP2;
-- WHERE절 & 서브쿼리 사용하여 데이터 수정
UPDATE DEPT_TEMP2 SET LOC = 'SEOUL' WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE DNAME='OPERATIONS');
SELECT * FROM DEPT_TEMP2;

-- 테이블에 있는 데이터 삭제 (DELETE, DROP)
CREATE TABLE EMP_TEMP2 AS SELECT*FROM EMP; -- EMP_TEMP2 테이블 생성
SELECT*FROM EMP_TEMP2;
DELETE FROM EMP_TEMP2 WHERE JOB ='MANAGER';
SELECT*FROM EMP_TEMP2; -- WHERE절을 사용한 데이터 일부분 삭제
DELETE FROM EMP_TEMP2 WHERE EMPNO IN (SELECT E.EMPNO FROM EMP_TEMP2 E, SALGRADE S WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE =3 AND DEPTNO =30);
SELECT*FROM EMP_TEMP2; -- 서브쿼리를 사용해 데이터 삭제(급여가 HISAL~LOSAL 사이에 있는 30번 부서의 사원만 삭제)
DELETE FROM EMP_TEMP2;-- 테이블에 있는 데이터 전체 삭제
SELECT * FROM EMP_TEMP2;

-- TEST PRACTICE (P.287~289) ☆
CREATE TABLE CHAP10HW_EMP AS SELECT*FROM EMP;
CREATE TABLE CHAP10HW_DEPT AS SELECT*FROM DEPT;
CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;

--  Q1.
SELECT * FROM CHAP10HW_DEPT;
INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (50,'ORACLE','BUSAN');
INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (60,'SQL','ILSAN') ;
INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (70,'SELECT','INCHEON') ;
INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (80,'DML','BUNDANG') ;
SELECT DEPTNO, DNAME,LOC FROM CHAP10HW_DEPT;

-- Q2.

INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)VALUES (7201, 'TEST_USER1','MANAGER',7788,TO_DATE('2016-01-02','YYYY-MM-DD'),4500,NULL,50);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)VALUES (7202, 'TEST_USER2','CLERK',7201,TO_DATE('2016-02-21','YYYY-MM-DD'),1800,NULL,50);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)VALUES (7203, 'TEST_USER3','ANALYST',7201,TO_DATE('2016-04-11','YYYY-MM-DD'),3400,NULL,60);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)VALUES (7204, 'TEST_USER4','MANAGER',7201,TO_DATE('2016-05-31','YYYY-MM-DD'),2700,300,60);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)VALUES (7205, 'TEST_USER5','MANAGER',7201,TO_DATE('2016-07-20','YYYY-MM-DD'),2600,NULL,70);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)VALUES (7206, 'TEST_USER6','MANAGER',7201,TO_DATE('2016-09-08','YYYY-MM-DD'),2600,NULL,70);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)VALUES (7207, 'TEST_USER7','MANAGER',7201,TO_DATE('2016-10-28','YYYY-MM-DD'),2300,NULL,80);
INSERT INTO CHAP10HW_EMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)VALUES (7208, 'TEST_USER8','MANAGER',7201,TO_DATE('2016-03-09','YYYY-MM-DD'),1200,NULL,80);
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO FROM CHAP10HW_EMP;

UPDATE CHAP10HW_EMP SET DEPTNO = 70 WHERE DEPTNO = 50 AND SAL> ( SELECT AVG(SAL) FROM CHAP10HW_EMP WHERE DEPTNO =50 );
SELECT*FROM CHAP10HW_EMP;

UPDATE CHAP10HW_EMP SET DEPTNO = 80 WHERE DEPTNO =60 AND SELECT CHAP10HW_EMP * FROM WHERE HIREDATE > SELECT (MIN(HIREDATE) FROM CHAP10HW_EMP

--- ☆

-- 트래잭션 제어와 세션
-- 트래잭션을 제어하는 명령어
--1. DEPT 테이블 복사해 DEPT_TCL 테이블 생성
CREATE TABLE DEPT_TCL AS SELECT*FROM DEPT;
SELECT*FROM DEPT_TCL;
--2. 명령어를 실행해 확인하기 (INSERT, UPDATE,DELETE)
INSERT INTO DEPT_TCL VALUES(50,'DATABASE','SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL_ WHERE DNAME = 'RESEARCH';
SELECT*FROM DEPT_TCL;
--3. ROLLBACK (트래잭션을 취소하고 싶을때)
ROLLBACK;
SELECT*FROM DEPT_TCL;
--4. COMMIT (트래잭션을 영원히 반영하고 싶을 때)
INSERT INTO DEPT_TCL VALUES(50,'NETWORK','SEOUL');
UPDATE DEPT_TCL SET LOC= 'BUSAN' WHERE DEPTNO = 20;
DELETE FROM DEPT_TCL WHERE DEPTNO = 40;
SELECT * FROM DEPT_TCL;
COMMIT;

-- 세션 읽기와 일관성 (순서가 아주 중요)
-- 세션A는 토드에서 세션B는 SQL*PLUS에 SCOTT 계정으로 접속해서 확인
SELECT*FROM DEPT_TCL; -- 조회 결과가 같음
DELETE FROM DEPT_TCL WHERE DEPTNO=50;
SELECT*FROM DEPT_TCL;
COMMIT;
SELECT*FROM DEPT_TCL;

-- LOCK (수정중인 데이터 접근을 막음)


-- 세션A는 토드에서 세션B는 SQL*PLUS에 SCOTT 계정으로 접속해서 확인
SELECT*FROM DEPT_TCL; -- 조회 결과가 가타음
UPDATE DEPT_TCL SET LOC = 'SEOUL' WHERE DEPTNO = 30;
SELECT*FROM DEPT_TCL;



-- ☆(~P.309)

-- 데이터 정의어 사용하기 (정의어는 자동 COMMIT 됨으로 ROLLBACK이 불가하다)

-- CREATE 사용하기 (새로운 테이블 생성)
CREATE TABLE EMP_DDL( EMPNO NUMBER(4), ENAME VARCHAR2(10), JOB VARCHAR2(9), MGR NUMBER(4), HIREDATE DATE, SAL NUMBER(7,2), COMM NUMBER(7,2), DEPTNO NUMBER(2));
DESC EMP_DDL;
-- 기존 테이블 열 구조와 데이터를 복사하여 새 테이블 생성
CREATE TABLE DEPT_DDL AS SELECT*FROM DEPT;
DESC DEPT_DDL;
SELECT * FROM DEPT_DDL;
-- 다른 테이블의 일부 데이터만 복사하여 새 테이블 생성
CREATE TABLE EMP_DDL_30 AS SELECT*FROM EMP WHERE DEPTNO =30;
SELECT*FROM EMP_DDL_30
-- 기존 테이블의 열 구조만 복사하여 새 테이블 생성
CREATE TABLE EMPDEPT_DDL AS SELECT E.EMPNO, E.ENAME, E.JOB,E.MGR,E.HIREDATE,E.SAL,E.COMM,D.DEPTNO,D.DNAME,D.LOC FROM EMP E, DEPT D WHERE 1<>1;
SELECT*FROM EMPDEPT_DDL; -- 1<>1 은 항상 FALSE 이기 때문에 열구조는 저장 되지만 데이터는 저장되지 않음

-- ALTER 사용하기
-- EMP 테이블을 복사해 EMP_ALTER 테이블 생성
CREATE TABLE EMP_ALTER AS SELECT*FROM EMP;
SELECT*FROM EMP_ALTER;
-- ADD 사용 ( 열 추가)
ALTER TABLE EMP_ALTER ADD HP VARCHAR2(20);
SELECT*FROM EMP_ALTER;
-- RENAME(열 이름 변경)
ALTER TABLE EMP_ALTER RENAME COLUMN HP TO TEL;
SELECT*FROM EMP_ALTER;
-- MODIFY ( 열 자료형 변경)
ALTER TABLE EMP_ALTER MODIFY EMPNO NUMBER(5); -- EMPNO 자리수를 NUMBER(4)에서 (5)로 길이 변경
DESC EMP_ALTER;
-- DROP (특정 열을 삭제)
ALTER TABLE EMP_ALTER DROP COLUMN TEL;
SELECT * FROM EMP_ALTER;

-- RENAME 사용하기 (테이블 변경)
--테이블 이름 변경
RENAME EMP_ALTER TO EMP_RENAME;
DESC EMP_ALTER; --이름이 변경되었으므로 원래 테이블 이름을 사용할 수 없음
SELECT*FROM EMP_RENAME; -- 변경된 테이블 이름으로 조회

-- TRUNCATE 사용하기 (테이블 데이터 삭제)
-- EMP_RENAME 테이블 전체 데이터 삭제
TRUNCATE TABLE EMP_RENAME;
SELECT*FROM EMP_RENAME;

-- DROP 사용하기 ( 테이블 삭제)
DROP TABLE EMP_RENAME;
DESC EMP_RENAME; -- 삭제되었기 때문에 조회 불가능

-- TEST PRACTICE (P.324~P.325)
--Q1.
CREATE TABLE EMP_HW AS SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EMP;
SELECT*FROM EMP_HW;
DROP TABLE EMP_HW;
CREATE TABLE EMP_HW(EMPNO NUMBER(4),ENAME VARCHAR2(10), JOB VARCHAR2 (9), MGR NUMBER(4), HIREDATE DATE, SAL NUMBER (7,2), COMM NUMBER(7,2),DEPTNO NUMBER(2));
DESC EMP_HW;

-- Q2.
ALTER TABLE EMP_HW ADD BIGO VARCHAR2 (20);
SELECT * FROM EMP_HW;
DESC EMP_HW;

-- Q3.
ALTER TABLE EMP_HW MODIFY BIGO NUMBER(30);
DESC EMP_HW;

-- Q4.
ALTER TABLE EMP_HW RENAME COLUMN BIGO TO REMARK;
DESC EMP_HW;

-- Q5.
DROP TABLE EMP_HW;
CREATE TABLE EMP_HW AS SELECT*FROM EMP;
ALTER TABLE EMP_HW ADD REMARK NUMBER(20);
UPDATE EMP_HW SET REMARK = NULL; 
SELECT*FROM  EMP_HW;


-- Q6.
DROP TABLE EMP_HW;
SELECT *FROM EMP_HW;
DESC EMP_HW;


-- 객체 종류 (DB를 저장한 데이터사전)
-- DICT ( SCOTT 계정에서 사용가능 데이터사전)
SELECT*FROM DICT;
-- DICTIONARY ( SCOTT 계정에서 사용가능 데이터사전)
SELECT*FROM DICTIONARY;
-- USER_(접두어를 가진 데이터사전)
SELECT TABLE_NAME FROM USER_TABLES; -- SCOTT 계정이 가지고있는 객체정보조회
-- ALL_ (접두어를 가진 데이터사전)
SELECT OWNER, TABLE_NAME FROM ALL_TABLES; -- SCOTT 계정이 가지고있는 객체정보조회
-- DBA_ (접두어를 가진 데이터사전)
SELECT * FROM DBA_TABLES; -- DB관리 권한을 가진 사용자만 조회가능 SCOTT에선 조회가안됨

-- 인덱스 (INDEX)/(SCOTT 계정일때)
-- 인덱스 정보 조회
SELECT * FROM USER_INDEXES;
-- 인덱스 컬럼 정보 조회
SELECT * FROM USER_IND_COLUMNS;

-- 인덱스 생성
CREATE INDEX IDX_EMP_SAL ON EMP(SAL);
SELECT * FROM USER_IND_COLUMNS;

-- 인덱스 삭제
DROP INDEX IDX_EMP_SAL ;
SELECT*FROM USER_IND_COLUMNS;


-- 뷰 (가상테이블)
-- SCOTT 계정은 뷰 생성 권한이 없으므로 SYSTEM 계정으로 접속해서 권한 부여해준 후 생성해야함
-- 뷰 생성 (CREATE문으로 생성가능) 
CREATE VIEW VW_EMP20 AS (SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO =20);
DROP TABLE VM_EMP20;
CREATE VIEW VW_EMP20 AS (SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO =20);
SELECT* FROM USER_VIEWS;
SELECT*FROM VW_EMP20; -- 생성한 뷰 조회
-- 뷰 삭제
DROP VIEW VM_EMP20;

-- 인라인뷰 (일회성 뷰) 사용
-- ROWNUM (저장된 행을 순서대로 매긴 일련번호) 추가 조회
SELECT ROWNUM, E.* FROM EMP E;
SELECT ROWNUM, E.* FROM EMP E ORDER BY SAL DESC; -- SAL순서대로 정렬했지만 ,ROWNUM은 위에 조회한 순서대로 적혀있음
-- 서브쿼리를 사용한 인라인 뷰
SELECT ROWNUM,E.* FROM (SELECT*FROM EMP E ORDER BY SAL DESC) E;
-- WITH절 사용한 인라인 뷰
WITH E AS(SELECT *FROM EMP ORDER BY SAL DESC) SELECT ROWNUM, E.* FROM E;
-- 인라인뷰로 TOP-N 추출
SELECT ROWNUM, E.* FROM (SELECT * FROM EMP E ORDER BY SAL DESC) E WHERE ROWNUM <=3; -- (서브쿼리 사용)
WITH E AS (SELECT*FROM EMP ORDER BY SAL DESC) SELECT ROWNUM, E.* FROM E WHERE ROWNUM <=3; -- (WITH절 사용)


-- 시퀀스 !!!!!!!!!!!!!!
-- 시퀀스 생성
CREATE TABLE DEPT_SEQUENCE AS SELECT*FROM DEPT WHERE 1<>1;
SELECT*FROM DEPT_SEQUENCE; -- 열만 가져오고 데이터는 없이 복사
CREATE SEQUENCE SEO_DEPT_SEQUENCE INCREMENT BY 10 START WITH 10 MAXVALUE 90 MINVALUE 0 NOCYCLE CACHE 2; -- 시퀀스 생성
SELECT*FROM USER_SEQUENCES;
RENAME SEO_DEPT_SEQUENCE TO SEQ_DEPT_SEQUENCE;
SELECT*FROM USER_SEQUENCES;

-- 시퀀스 사용 (.NEXTVAL)
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC) VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL,'DATABASE','SEOUL');
SELECT*FROM DEPT_SEQUENCE ORDER BY DEPTNO;
-- 마지막으로 생성된 시퀀스 확인 (.CURRVAL)
SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;
-- 생성된 순번을 반복 사용해 INSERT문 실행
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME,LOC) VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE','SEOUL');
SELECT*FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--시퀀스 수정 (ALTER)
ALTER SEQUENCE SEQ_DEPT_SEQUENCE INCREMENT BY 3 MAXVALUE 99 CYCLE; --최대값 99, 증가값 3, 옵션 CYCLE로 변경
SELECT*FROM USER_SEQUENCES;
-- 수정 된 시퀀스로 INSERT문 사용
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC) VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE','SEOUL');
SELECT*FROM DEPT_SEQUENCE ORDER BY DEPTNO;
-- CYCLE 옵션을 사용해 시퀀스 최댓값 도달 후 결과 조회
INSERT INTO DEPT_SEQUENCE (DEPTNO,DNAME,LOC) VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL,'DATABASE','SEOUL'); 
SELECT*FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--시퀀스 삭제
DROP SEQUENCE SEQ_DEPT_SEQUENCE;
SELECT*FROM USER_SEQUENCES;

-- 동의어
-- 동의어 생성 (SYSTEM 가서 SCOTT에 권한부여 후 사용)
CREATE SYNONYM E FOR EMP;
SELECT*FROM E;

-- 동의어 삭제
DROP SYNONYM E;

-- TEST PRACTICE (P.357~358)
-- Q1.
CREATE TABLE EMPIDX AS SELECT *FROM EMP WHERE 1<>1;
SELECT*FROM EMPIDX;
-- Q2.
CREATE VIEW EMPIDX_OVER15K AS (SELECT EMPNO, ENAME, JOB DEPTNO,SAL,COMM FROM EMPIDX WHERE SAL>1500)WITH CHECK OPTION CONSTRAINT COMM_CHECK ;
DROP VIEW EMPIDX_OVER15K;
CREATE VIEW EMPIDX_OVER15K AS (SELECT EMPNO, ENAME, JOB DEPTNO,SAL,COMM FROM EMP WHERE SAL>1500)WITH CHECK OPTION CONSTRAINT COMM_CHECK ;
DROP VIEW EMPIDX_OVER15K;
CREATE VIEW EMPIDX_OVER15K AS (SELECT EMPNO, ENAME, JOB DEPTNO,SAL,COMM FROM EMP WHERE SAL>1500)WITH CHECK OPTION CONSTRAINT COMMN_CHECK;
DROP VIEW EMPIDX_OVER15K;
CREATE OR REPLACE VIEW EMPIDX_OVER15K AS SELECT EMPNO, ENAME, JOB, DEPTNO,SAL, CASE WHEN COMM IS NOT NULL THEN 'O' ELSE 'X' END AS COMM  FROM EMP  WHERE SAL>1500 WITH CHECK OPTION CONSTRAINT COMM_CHECK;
SELECT*FROM USER_VIEWS;
SELECT*FROM EMPIDX_OVER15K;
-- ☆ (~P.358) Q3. (해야됨)

-- 제약 조건의 종류
-- NOT NULL (빈값 허용 안됨)
-- 테이블 생성시 NOT NULL 설정
CREATE TABLE TABLE_NOTNULL( LOGIN_ID VARCHAR2(20) NOT NULL, LOGIN_PWD VARCHAR2(20) NOT NULL, TEL VARCHAR2(20));
DESC TABLE_NOTNULL;
-- NOT NULL에 NULL값 넣기
INSERT INTO TABLE_NOTNULL (LOGIN_ID,LOGIN_PWD,TEL) VALUES ('TEST_ID_01',NULL,'010-1234-5678') -- NULL 값이 아닌 값을 지정하도록 하고있어서 오류남
-- 제약 조건 없는 TEL 열에 NULL 입력
INSERT INTO TABLE_NOTNULL (LOGIN_ID,LOGIN_PWD) VALUES('TEST_ID_01','1234');
SELECT*FROM TABLE_NOTNULL;
--  NOT NULL 제약 조건이 있는 열데이터를 NULL 값으로 업데이트
UPDATE TABLE_NOTNULL SET LOGIN_PWD = NULL WHERE LOGIN_ID='TEST_ID_01'; -- 수정이 불가능합

-- 제약 조건 확인 !!!!!
SELECT OWNER,CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME FROM USER_CONSTRAINTS;
-- 제약 조건 이름 직접 지정
CREATE TABLE TABLE_NOTNULL2( LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL, LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL, TEL VARCHAR2(20));
SELECT OWNER,CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME FROM USER_CONSTRAINTS;

-- 이미 생성한 테이블에 제약 조건 걸기
-- TEL 열에 NOT NULL 조건 추가
ALTER TABLE TABLE_NOTNULL MODIFY(TEL NOT NULL); -- 조건대상에 추가제약조건에 맞지 않는대상이 존재하기 때문에 오류가 남
UPDATE TABLE_NOTNULL SET TEL='010-1234-5678' WHERE LOGIN_ID = 'TEST_ID_01'; -- UPDATE 문을 사용하여 NULL이 아닌 데이터로 수정
SELECT * FROM TABLE_NOTNULL;

-- 다시 TEL에 NOT NULL 조건 추가지정하기
ALTER TABLE TABLE_NOTNULL MODIFY(TEL NOT NULL);
SELECT OWNER, CONSTRAINT_NAME,CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS; --NULL 데이터를 위에서 없앴으므로 수정이 됨

-- 제약조건에 지정된 이름 추가하기
ALTER TABLE TABLE_NOTNULL2 MODIFY (TEL CONSTRAINT TBLNN_TEL_NN NOT NULL);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE,TABLE_NAME FROM USER_CONSTRAINTS;

-- TABLE_NOTNULL2 테이블 열 구조 확인
DESC TABLE_NOTNULL2;

-- 생성된 제약 조건 이름 변경
ALTER TABLE TABLE_NOTNULL2 RENAME CONSTRAINT TBLNN_TEL_NN TO TBLNN2_TEL_NN;
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS;

-- 제약 조건 삭제
ALTER TABLE TABLE_NOTNULL2 DROP CONSTRAINT TBLNN2_TEL_NN;
DESC TABLE_NOTNULL2;-- 제약조건을 삭제해서 TEL열은 NULL이 저장될 수있는 열이 됨

-- UNIQUE (중복되지 않는 값)
-- 테이블 생성하며 제약조건 지정
CREATE TABLE TABLE_UNIQUE ( LOGIN_ID VARCHAR2(20) UNIQUE, LOGIN_PWD VARCHAR2(20) NOT NULL, TEL VARCHAR2(20));
DESC TABLE_UNIQUE;
-- 제약 조건 확인
SELECT OWNER, CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='TABLE_UNIQUE';
-- 중복 안됨
INSERT INTO TABLE_UNIQUE (LOGIN_ID,LOGIN_PWD,TEL) VALUES('TEST_ID_01','PWD01','010-1234-5678');
SELECT*FROM TABLE_UNIQUE;
INSERT INTO TABLE_UNIQUE (LOGIN_ID,LOGIN_PWD,TEL) VALUES ('TEST_ID_01','PWD01','010-1234-5678');-- 중복이 안되기 때문에 오류발생

-- 테이블에 데이터 입력하기
INSERT INTO TABLE_UNIQUE (LOGIN_ID,LOGIN_PWD,TEL)VALUES ('TEST_ID_02','PWD01','010-1234-5678');
SELECT*FROM TABLE_UNIQUE;

-- UNIQUE 제약이 걸린 열에 NULL 값 입력하기
INSERT INTO TABLE_UNIQUE (LOGIN_ID,LOGIN_PWD,TEL) VALUES(NULL,'PWD01','010-2345-6789');
SELECT*FROM TABLE_UNIQUE;
-- UPDATE 사용해서 수정하기 (제약이 걸려있으므로 중복 발생으로 실행안됨)
UPDATE TABLE_UNIQUE SET LOGIN_ID='TEST_ID_01' WHERE LOGIN_ID IS NULL;

-- 테이블을 생성하며 제약 조건 이름 직접 지정
CREATE TABLE TABLE_UNIQUE2(LOGIN_ID VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNID_UNQ UNIQUE, LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNPW_NN NOT NULL, TEL VARCHAR2(20));
-- UNIQUE_CONSTRAINTS를 사용해 생성한 제약조건 확인하기 
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';

-- 생성한 테이블에 제약 조건 지정
ALTER TABLE TABLE_UNIQUE MODIFY(TEL UNIQUE);-- 이미 TEL 열에 중복된 열이 있기 때문에 오류, 제약 조건을 추가할때 해당열에서 조건에 충족되지 않는 데이터를 삭제 후 진행해야 함
-- TEL 열 값을 모두 NULL로 변경
UPDATE TABLE_UNIQUE SET TEL = NULL;
SELECT * FROM TABLE_UNIQUE;
--TEL 값에 UNIQUE 제약 조건 설정
ALTER TABLE TABLE_UNIQUE MODIFY(TEL UNIQUE);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';


-- 생성한 테이블에 제약 조건 이름을 직접 지정하거나 바꾸기
ALTER TABLE TABLE_UNIQUE2 MODIFY (TEL CONSTRAINT TBLUNQ_TELUNQ UNIQUE);
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';


-- 제약 조건 삭제 (DROP CONSTRAINT사용)
ALTER TABLE TABLE_UNIQUE2 DROP CONSTRAINT TBLUNQ_TELUNQ;
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'TABLE_UNIQUE%';



-- PRIMARY KEY (유일한 값)
-- 테이블 생성하며 제약 조건 지정 
CREATE TABLE TABLE_PK (LOGIN_ID VARCHAR2(20) PRIMARY KEY, LOGIN_PWD VARCHAR2(20) NOT NULL, TEL VARCHAR2(20));
DESC TABLE_PK;
-- 생성한 PRIMARY KEY 확인
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'TABLE_PK%';
-- 생성한 PRIMARY KEY 로 자동생성 INDEX 확인
SELECT INDEX_NAME, TABLE_OWNER, TABLE_NAME FROM USER_INDEXES WHERE TABLE_NAME LIKE 'TABLE_PK%';
-- 제약 조건 이름 직접 지정해 테이블 생성
CREATE TABLE TABLE_PK2( LOGIN_ID VARCHAR2(20) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY, LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLPK2_LGNPW_NN NOT NULL, TEL VARCHAR2 (20));
DESC TABLE_PK2;
-- PRIMARY KEY 제약 조건을 지정한 열 확인 (중복 값 입력했을 때)
INSERT INTO TABLE_PK (LOGIN_ID, LOGIN_PWD,TEL) VALUES ('TEST_ID_01','PWD01','010-1234-5678');
SELECT*FROM TABLE_PK;
INSERT INTO TABLE_PK (LOGIN_ID, LOGIN_PWD,TEL) VALUES ('TEST_ID_01','PWD01','010-1234-5678'); -- 중복을 허용하지 않아 오류남
-- PRIMARY KEY 제약 조건을 지정한 열 확인 (NULL 값 입력 했을 때)
-- NULL값을 명시적으로 입력
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD,TEL) VALUES (NULL, 'PWD02','010-2345-6789'); -- NULL값을 허용하지않아서 오류
-- NULL값을 암시적으로 입력
INSERT INTO TABLE_PK(LOGIN_ID, LOGIN_PWD,TEL) VALUES (NULL, 'PWD02','010-2345-6789');-- NULL값을 허용하지않아서 오류


-- CREATE 문에서 제약 조건 지정하는 방법
CREATE TABLE TABLE_NAME ( COL1 VARCHAR2 (20) CONSTRAINT CONSTRAINT_NAME PRIMARY KEY, COL2 VARCHAR2(20) NOT NULL, COL3 VARCHAR2 (20)); --C0P1만 이름 지정
DESC TABLE_NAME;
CREATE TABLE TABLE_NAME ( COL1 VARCHAR2 (20) , COL2 VARCHAR2(20), COL3 VARCHAR2 (20), PRIMARY KEY (COL1), CONSTRAINT CONSTRAINT_NAME UNIQUE(COL2)); --이렇게도 가능

-- FOREIGN KEY ( 다른 테이블과 관계를 정의하는데 사용하는 제약 조건)
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, R_OWNER, R_CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME IN ('EMP', 'DEPT');
-- FOREIGN KEY가 참조하는 열에 존재하지 않는 데이터 입력
INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(9999,'홍길동','CLERK','7788', TO_DATE('2017/04/30','YYYY/MM/DD'), 1200,NULL,50); -- DEPTNO에 50이 없기 때문에 오류

--FOREIGN KEY 지정하기 !!!!!!!!!!!!
--테이블 생성
CREATE TABLE DEPT_FK (DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY, DNAME VARCHAR2(14), LOC VARCHAR2(13));
DESC DEPT_FK;
-- EMP_FK 테이블 생성하기
CREATE TABLE EMP_FK ( 
EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2 (10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO));

DESC EMP_FK;


--EMP _FK 테이블에 데이터 삽입하기 (DEPTNO 데이터가 DEPT_FK 테이블에 없어서 오류)
INSERT INTO EMP_FK VALUES(9999, 'TEST_NAME','TEST_JOB',NULL,TO_DATE('2001/01/01','YYYY/MM/DD'), 3000, NULL,10); 

-- DEPT_FK 테이블에 데이터를 삽입한 후 ,EMP_FK에 데이터를 삽입
-- 1) DEPT_FK 테이블에 데이터 삽입
INSERT INTO DEPT_FK VALUES(10,'TEST_DNAME','TEST_LOC');
SELECT *FROM DEPT_FK;
-- 2) EMP_FK 테이블에 데이터 삽입
INSERT INTO EMP_FK VALUES(9999, 'TEST_NAME','TEST_JOB',NULL,TO_DATE('2001/01/01','YYYY/MM/DD'), 3000, NULL,10); 
SELECT *FROM EMP_FK;


-- FOREIGN KEY로 참조 데이터 삭제하기
-- DEPT_FK 테이블의 DEPTNO 10 삭제하기
DELETE FROM DEPT_FK WHERE DEPTNO = 10;
-- DEPTNO 를 참조하는 열 데이터를 먼저 삭제하거나 수정하거나 FOREIGH KEY 제약조건을 해제해야 삭제가 가능

-- CHECK ( 데이터 형태와 범위를 정하는 제약조건 )
-- 테이블을 생성하면서 CHECK 제약 조건 설정
CREATE TABLE TABLE_CHECK( LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY, LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK (LENGTH(LOGIN_PWD)>3), TEL VARCHAR2(20));
DESC TABLE_CHECK;

-- CHCEK 조건에 맞지 않는 예
INSERT INTO TABLE_CHECK VALUES('TEST_ID','123','010-1234-5678'); -- 제약 조건에 비밀번호를 3자리를 넘게 해놨는데 안넘어서 오류

-- CHECK 조건에 맞는 예
INSERT INTO TABLE_CHECK VALUES('TEST_ID','1234','010-1234-5678'); -- 제약 조건에 맞아서 실행됨
SELECT *FROM TABLE_CHECK;

-- CHECK 제약 조건 확인하기
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE,TABLE_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME LIKE 'TABLE_CHECK';

-- DEFAULT (기본값 지정)
-- 테이블을 생성할때 DEFAULT 제약 조건 설정
CREATE TABLE TABLE_DEFAULT ( LOGIN_ID VARCHAR2 (20) CONSTRAINT TBLCK2_LOGINID_PK PRIMARY KEY, LOGIN_PWD VARCHAR2(20) DEFAULT '1234', TEL VARCHAR2(20));
DESC TABLE_DEFAULT;

-- INSERT 문을 사용해 지정한 기본값 테스트

INSERT INTO TABLE_DEFAULT VALUES ('TEST_ID', NULL, '010-1234-5678');
INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL) VALUES ('TEST_ID2','010-1234-5678');
SELECT * FROM TABLE_DEFAULT; -- NULL 을 지정한 곳은 비어있지만 두번째에는 기본값이 들어가있음

-- 사용자 관리 
-- 1. 사용자 생성
CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE; -- SCOTT 계정으로 사용자 생성 (권한이 없는 일반 사용자이기 때문에 생성이 안됨)
-- CONN 명령어를 사용해 계정에 권한을 부여함
-- 2. 사용자 정보 조회
SELECT * FROM ALL_USERS WHERE USERNAME = 'ORCLSTUDY'; -- USENAME이 ORCLSTUDY인 모든 유저를 조회
SELECT * FROM DBA_USERS WHERE USERNAME = 'ORCLSTUDY'; -- DBA 권한을 부여받은 계정 조회
SELECT * FROM DBA_OBJECTS WHERE OWNER = 'ORCLSTUDY';
SELECT * FROM ALL_USERS -- 모든 유저를 조회

-- 3. 오라클 사용자의 변경과 삭제
-- 시스템 계정에 접속해 PW 변경 / ALTER USER ORCLSTUDY IDENTIFIED BY ORCL; 
-- 시스템 계정에 접속해 사용자 삭제 / DROP USER ORCLSTUDY;
-- 시스템 계정에 접속해 사용자와 객체 모두 삭제 / DROP USER ORCLSTUDY CASCADE;

-- 권환 관리
-- 1. 시스템 계정으로 접속후 사용자 생성 CREATE USER (ID) IDENTIFIED BY (PW);
-- 2. 사용자 권한 부여 GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO (ID);
-- 3. 시스템 권환 취소 REBOKE (권한) FROM (ID,롤 이름,PUBLIC);

-- 객체 권한
-- 1. 사용자에게 테이블 권한 부여 GRANT 명령어나 정의어 ON 객체명 TO ID;
-- 2. 테이블의 여러권한을 한번에 부여 GRANT 명령어,정의어 ON 객체명 TO ID; 쉼표를 넣어 여러개 지정
-- 3. 객체 권한 취소 REVOKE 명령어나 정의어 ON 객체명, FROM ID;

-- 롤 관리 ( CONNECT, RESOURCE, DBA)
-- 1. 시스템 계정으로 롤생성 및 권한 부여 (CREATE ROLE 롤명); GRANT 권한 TO 롤명;
-- 2. 부여된 롤과 권한 확인 (SELECT* FROM USER_SYS_PRIVS, USER_ROLE_PRIVS/// 데이터 관리 권한을 가진 계정은 DBA_SYS_PRIVS, DBA_ROLE,PRIVS 사용)
-- 3. 부여된 롤 취소 DROP ROLE 롤명;

-- ☆(25/06/05~P.416까지 했음)







